/*
 * Port_cfg.h
 *
 *  Created on: Jan 18, 2021
 *      Author: Rdwa Salah
 */
/*
 * These macros are used to: Define the Initial mode for the all pins
 */
#ifndef PORT_CFG_H_
#define PORT_CFG_H_

/* Initial Mode for the pins */
#define PORT_u8PIN_0_INIT_MODE		PORT_u8OUTPUT_LOW	//PA0
#define PORT_u8PIN_1_INIT_MODE		PORT_u8OUTPUT_LOW   //PA1
#define PORT_u8PIN_2_INIT_MODE		PORT_u8OUTPUT_LOW   //PA2
#define PORT_u8PIN_3_INIT_MODE		PORT_u8OUTPUT_LOW   //PA3
#define PORT_u8PIN_4_INIT_MODE		PORT_u8OUTPUT_LOW   //PA4
#define PORT_u8PIN_5_INIT_MODE		PORT_u8OUTPUT_LOW   //PA5
#define PORT_u8PIN_6_INIT_MODE		PORT_u8OUTPUT_LOW   //PA6
#define PORT_u8PIN_7_INIT_MODE		PORT_u8OUTPUT_LOW   //PA7
#define PORT_u8PIN_8_INIT_MODE		PORT_u8OUTPUT_LOW   //PB0
#define PORT_u8PIN_9_INIT_MODE		PORT_u8OUTPUT_LOW   //PB1
#define PORT_u8PIN_10_INIT_MODE		PORT_u8OUTPUT_LOW   //PB2
#define PORT_u8PIN_11_INIT_MODE		PORT_u8OUTPUT_LOW   //PB3
#define PORT_u8PIN_12_INIT_MODE		PORT_u8OUTPUT_LOW   //PB4
#define PORT_u8PIN_13_INIT_MODE		PORT_u8OUTPUT_LOW   //PB5
#define PORT_u8PIN_14_INIT_MODE		PORT_u8OUTPUT_LOW   //PB6
#define PORT_u8PIN_15_INIT_MODE		PORT_u8OUTPUT_LOW   //PB7
#define PORT_u8PIN_16_INIT_MODE		PORT_u8OUTPUT_LOW   //PC0
#define PORT_u8PIN_17_INIT_MODE		PORT_u8OUTPUT_LOW   //PC1
#define PORT_u8PIN_18_INIT_MODE		PORT_u8OUTPUT_LOW   //PC2
#define PORT_u8PIN_19_INIT_MODE		PORT_u8OUTPUT_LOW   //PC3
#define PORT_u8PIN_20_INIT_MODE		PORT_u8OUTPUT_LOW   //PC4
#define PORT_u8PIN_21_INIT_MODE		PORT_u8OUTPUT_LOW   //PC5
#define PORT_u8PIN_22_INIT_MODE		PORT_u8OUTPUT_LOW   //PC6
#define PORT_u8PIN_23_INIT_MODE		PORT_u8OUTPUT_LOW   //PC7
#define PORT_u8PIN_24_INIT_MODE		PORT_u8OUTPUT_LOW   //PD0
#define PORT_u8PIN_25_INIT_MODE		PORT_u8OUTPUT_LOW   //PD1
#define PORT_u8PIN_26_INIT_MODE		PORT_u8INPUT_PULL_UP   //PD2
#define PORT_u8PIN_27_INIT_MODE		PORT_u8OUTPUT_LOW   //PD3
#define PORT_u8PIN_28_INIT_MODE		PORT_u8OUTPUT_LOW   //PD4
#define PORT_u8PIN_29_INIT_MODE		PORT_u8OUTPUT_LOW   //PD5
#define PORT_u8PIN_30_INIT_MODE		PORT_u8OUTPUT_LOW   //PD6
#define PORT_u8PIN_31_INIT_MODE		PORT_u8OUTPUT_LOW   //PD7

#endif /* PORT_CFG_H_ */
